### ISSUE TITLE
cannot find macro `parse_macro_input` in this scope

### ISSUE THREAD

**Issue by jplatte** [jakobhellermann/cargo-watt#8]
It seems like your syn fork is broken. I'd open an issue there, but that doesn't seem to be possible. Both `syn::parse_macro_input!` and `syn::parse` (the function, not the module) seem to be missing from it and this results in most crates from watt-contrib failing to compile.

**Comment by jakobhellermann** [comment]
I recently updated the fork, can you check if the problem still persists? Which crate are you using?

**Comment by jplatte** [comment]
serde_derive is one that used to fail. It compiles now (but still fails to verify – https://github.com/jakobhellermann/watt-contrib/issues/2).
